In [2]:
g = lambda x: x**2

In [4]:
g(4)

16

In [19]:
def i(f) : return lambda x: x*f + x

In [20]:
s = i(2) #passing f value first
s(8) #passing x value to complete calculation of equation

24

In [100]:
import pandas as pd
df = pd.read_csv(r"\\USHOUHOME02\vakkam\Desktop\Sample Perf.csv",delimiter=',')
df['REINVESTMENT_FACTOR'] = ((df[:-1].REPORT_CONTRIB_SUM_CI_RATE[::-1]+1).cumprod())
print(df)

   PERFORM_DATE  REPORT_CONTRIB_SUM_CI_RATE  REINVESTMENT_FACTOR
0      1/1/2017                    0.000000             1.018167
1      1/2/2017                    0.000495             1.018167
2      1/3/2017                    0.006535             1.017663
3      1/4/2017                    0.006328             1.011055
4      1/5/2017                    0.000930             1.004698
5      1/6/2017                    0.002419             1.003764
6      1/7/2017                    0.000000             1.001342
7      1/8/2017                    0.000000             1.001342
8      1/9/2017                   -0.003557             1.001342
9     1/10/2017                    0.000755             1.004917
10    1/11/2017                    0.001517             1.004159
11    1/12/2017                   -0.000240             1.002638
12    1/13/2017                    0.001302             1.002878
13    1/14/2017                    0.000000             1.001574
14    1/15/2017                    0.000000             1.001574
15    1/16/2017                   -0.000949             1.001574
16    1/17/2017                   -0.001435             1.002525
17    1/18/2017                    0.001650             1.003966
18    1/19/2017                   -0.003637             1.002313
19    1/20/2017                    0.002604             1.005972
20    1/21/2017                    0.000000             1.003359
21    1/22/2017                    0.000000             1.003359
22    1/23/2017                   -0.003580             1.003359
23    1/24/2017                    0.007617             1.006964
24    1/25/2017                    0.008964             0.999352
25    1/26/2017                   -0.003433             0.990473
26    1/27/2017                    0.001184             0.993885
27    1/28/2017                    0.000000             0.992710
28    1/29/2017                    0.000000             0.992710
29    1/30/2017                   -0.007290             0.992710
30    1/31/2017                    0.000201                  NaN